# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6QiwKbz224j6Wm4tHq2fuZSLDUFrJar
"""

# 在 Colab 中先运行本单元格。安装完成后如提示重启运行时，请重启后继续。
import subprocess, sys
subprocess.check_call([
    sys.executable, "-m", "pip", "install", "-q",
    "ortools>=9.10,<10", "pandas>=2.0", "openpyxl>=3.1",
])

from __future__ import annotations

import math
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Set, Tuple

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from ortools.sat.python import cp_model

# OR-Tools 버전 호환 패치 (수정판)
from ortools.sat.python import cp_model as _cp_module

def _status_name_compat(self, status=None):
    if status is not None:
        if hasattr(status, 'name'):
            return status.name
        return str(status)
    try:
        internal = self._checked_response.status
        return internal.name if hasattr(internal, 'name') else str(internal)
    except Exception:
        return 'UNKNOWN'

_cp_module.CpSolver.StatusName = _status_name_compat

# ===== 用户通常只需要修改这里 =====
INPUT_PATH = "/content/最终 (7) (1).xlsx"  # 例：/content/drive/MyDrive/舞团矩阵/ 或 /content/舞团成员空闲时间矩阵.xlsx
USE_GOOGLE_DRIVE = False
GOOGLE_DRIVE_PATH = "/content/drive/MyDrive/舞团矩阵"

EARLIEST_REHEARSAL_DATE = date(2026, 9, 4)
LAST_REHEARSAL_DATE = date(2026, 9, 19)
PERFORMANCE_DATE = date(2026, 9, 20)

MISSING_MEMBER_POLICY = "provisional"  # provisional / strict
SOFT_DAILY_HOUR_LIMIT = 6
HARD_DAILY_HOUR_LIMIT = 8
FREE_GAP_HOURS = 1                  # 当天累计空档不超过 1 小时不罚
MERGE_VISIT_GAP_HOURS = 1           # 两次排练相隔不超过 1 小时，视作一次到场
SOLVER_TIME_LIMIT_PER_STAGE = 90.0  # 每个优先级最多求解秒数
SOLVER_WORKERS = 8
RANDOM_SEED = 42

OUTPUT_DIR = Path("/content/排程结果")
OUTPUT_XLSX_NAME = "舞团排练排程结果.xlsx"


MEMBER_ORDER = ["衿", "菁", "幸", "思", "Ash", "嘎", "Siri", "Mo", "林", "郑", "若", "颜", "娄", "诗"]

SONGS = {
    "a": {"name": "恋爱的条件",              "difficulty": "简单", "members": ["衿", "菁", "嘎", "幸"]},
    "b": {"name": "Kiss of life-sweat",     "difficulty": "一般", "members": ["Ash", "幸", "嘎", "菁"]},
    "c": {"name": "KATSEYE-ANIMAL",         "difficulty": "一般", "members": ["Siri", "Mo", "幸", "思", "林"]},
    "d": {"name": "aespa-lemonadeA",        "difficulty": "简单", "members": ["郑", "嘎", "幸", "Ash"]},
    "e": {"name": "aespa-lemonadeB",        "difficulty": "简单", "members": ["菁", "Mo", "Siri", "若"]},
    "f": {"name": "thatsnono siri",          "difficulty": "简单", "members": ["Siri", "娄", "诗", "若", "思"]},
    "g": {"name": "rescene-pretty girl",    "difficulty": "简单", "members": ["郑", "衿", "若"]},
    "h": {"name": "少时-说出愿望吧",          "difficulty": "简单", "members": ["衿", "郑", "菁", "Mo", "若", "林"]},
    "i": {"name": "itzy-kill shot",          "difficulty": "简单", "members": ["娄", "衿", "思", "若"]},
    "j": {"name": "BTS-ineedu",              "difficulty": "困难", "members": ["思", "林", "菁", "Ash", "颜"]},
    "k": {"name": "blackpink-玩火",           "difficulty": "简单", "members": ["菁", "Siri", "若", "嘎"]},
    "l": {"name": "aespa-kissntell",         "difficulty": "一般", "members": ["郑", "Siri", "若", "诗"]},
}

REQUIRED_DURATIONS = {
    "困难": [3, 3, 3],
    "一般": [3, 2, 2],
    "简单": [2, 2],
}
SONG_SESSION_OVERRIDE = {
    "a": [2],      # 恋爱的条件：只排1×2h
    "c": [3, 2],   # KATSEYE-ANIMAL：1×3h＋1×2h
    "l": [3, 2],   # aespa-kissntell：1×3h＋1×2h
}

SLOT_START_HOURS = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0]
BOUNDARY_HOURS = SLOT_START_HOURS + [1]
SLOT_LABELS = [
    f"{BOUNDARY_HOURS[i]:02d}:00–{BOUNDARY_HOURS[i + 1]:02d}:00"
    for i in range(len(SLOT_START_HOURS))
]
H = len(SLOT_LABELS)

WEEKDAY_ZH = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]


@dataclass(frozen=True)
class Task:
    task_id: str
    song_id: str
    requirement_no: int
    duration: int


@dataclass(frozen=True)
class Candidate:
    date_idx: int
    start: int
    duration: int
    absent_member: str = ""   # "" = 全员到齐；否则为缺席成员姓名

    @property
    def hours(self) -> range:
        return range(self.start, self.start + self.duration)


@dataclass
class InputData:
    availability: Dict[str, Dict[date, List[int]]]
    global_allowed: Dict[date, List[int]]
    soft_avoid: Set[Tuple[str, date, int]]
    dates: List[date]
    warnings: List[str]
    source_files: List[str]


def canonical_member(value: object) -> str:
    text = str(value or "").strip().replace("→", "").strip()
    aliases = {"ash": "Ash", "siri": "Siri", "mo": "Mo"}
    return aliases.get(text.lower(), text)


def to_date(value: object) -> Optional[date]:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    parsed = pd.to_datetime(value, errors="coerce")
    if pd.isna(parsed):
        return None
    return parsed.date()


def normalize_slot_label(value: object) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip().replace("—", "–").replace("-", "–").replace("~", "–")
    nums = re.findall(r"(?<!\d)(\d{1,2})(?::(\d{2}))?", text)
    if len(nums) < 2:
        return None
    h1, m1 = int(nums[0][0]), int(nums[0][1] or 0)
    h2, m2 = int(nums[1][0]), int(nums[1][1] or 0)
    if m1 != 0 or m2 != 0:
        return None
    return f"{h1:02d}:00–{h2:02d}:00"


NORMALIZED_SLOT_TO_INDEX = {normalize_slot_label(label): i for i, label in enumerate(SLOT_LABELS)}


def coerce_binary(value: object, context: str, warnings: List[str]) -> int:
    if value in (1, True, "1", "✅", "🉑", "可"):
        return 1
    if value in (0, False, "0", "❌", "不可"):
        return 0
    if value is None or str(value).strip() == "":
        warnings.append(f"{context} 为空，已按 0（不可排练）处理。")
        return 0
    try:
        numeric = int(value)
        if numeric in (0, 1):
            return numeric
    except (TypeError, ValueError):
        pass
    raise ValueError(f"{context} 必须是 0/1，实际为：{value!r}")


def find_matrix_header(ws) -> Optional[Tuple[int, Dict[int, int]]]:
    max_row = min(ws.max_row or 0, 40)
    max_col = min(ws.max_column or 0, 40)
    for r in range(1, max_row + 1):
        values = [ws.cell(r, c).value for c in range(1, max_col + 1)]
        if not any(str(v or "").strip() == "日期" for v in values):
            continue
        slot_columns: Dict[int, int] = {}
        for c, value in enumerate(values, start=1):
            normalized = normalize_slot_label(value)
            if normalized in NORMALIZED_SLOT_TO_INDEX:
                slot_columns[NORMALIZED_SLOT_TO_INDEX[normalized]] = c
        if len(slot_columns) == H:
            return r, slot_columns
    return None


def extract_member_name(ws, sheet_name: str) -> str:
    for cell in (ws["A2"].value, ws["A1"].value):
        text = str(cell or "").strip()
        match = re.search(r"成员\s*[:：]\s*([^｜|]+)", text)
        if match:
            return canonical_member(match.group(1))
        if "｜" in text or "|" in text:
            first = re.split(r"[｜|]", text)[0].strip()
            if first and first not in {"全员共用", "排练软偏好"}:
                return canonical_member(first)
    for suffix in ("_有效时间矩阵", "_个人原始矩阵", "有效时间矩阵", "个人原始矩阵"):
        if sheet_name.endswith(suffix):
            prefix = sheet_name[: -len(suffix)].strip("_ ")
            if prefix:
                return canonical_member(prefix)
    return ""


def read_matrix_sheet(ws, label: str, warnings: List[str]) -> Dict[date, List[int]]:
    found = find_matrix_header(ws)
    if not found:
        raise ValueError(f"{label} 找不到完整的 14 个小时表头。")
    header_row, slot_columns = found
    date_col = next(
        c for c in range(1, (ws.max_column or 1) + 1)
        if str(ws.cell(header_row, c).value or "").strip() == "日期"
    )
    result: Dict[date, List[int]] = {}
    for r in range(header_row + 1, (ws.max_row or header_row) + 1):
        d = to_date(ws.cell(r, date_col).value)
        if d is None:
            continue
        row = [0] * H
        for h, c in slot_columns.items():
            row[h] = coerce_binary(ws.cell(r, c).value, f"{label} {d} {SLOT_LABELS[h]}", warnings)
        result[d] = row
    if not result:
        raise ValueError(f"{label} 没有读到任何日期数据。")
    return result


def parse_hour_range_to_slots(value: object) -> List[int]:
    text = str(value or "").replace("—", "–").replace("-", "–").replace("~", "–")
    nums = re.findall(r"(?<!\d)(\d{1,2})(?::(\d{2}))?", text)
    if len(nums) < 2:
        return []
    start_h, start_m = int(nums[0][0]), int(nums[0][1] or 0)
    end_h, end_m = int(nums[1][0]), int(nums[1][1] or 0)
    if start_m != 0 or end_m != 0 or start_h not in SLOT_START_HOURS:
        return []
    start_idx = SLOT_START_HOURS.index(start_h)
    end_idx = next((i for i in range(start_idx + 1, len(BOUNDARY_HOURS)) if BOUNDARY_HOURS[i] == end_h), None)
    if end_idx is None:
        return []
    return list(range(start_idx, end_idx))


def read_soft_preferences(ws, warnings: List[str]) -> Set[Tuple[str, date, int]]:
    result: Set[Tuple[str, date, int]] = set()
    header_row = None
    headers: Dict[str, int] = {}
    for r in range(1, min(ws.max_row or 0, 30) + 1):
        row_headers = {str(ws.cell(r, c).value or "").strip(): c for c in range(1, (ws.max_column or 0) + 1)}
        if {"成员", "日期", "可用时段"}.issubset(row_headers):
            header_row, headers = r, row_headers
            break
    if not header_row:
        return result
    for r in range(header_row + 1, (ws.max_row or header_row) + 1):
        member = canonical_member(ws.cell(r, headers["成员"]).value)
        d = to_date(ws.cell(r, headers["日期"]).value)
        slots = parse_hour_range_to_slots(ws.cell(r, headers["可用时段"]).value)
        if not member or not d:
            continue
        if not slots:
            warnings.append(f"排练偏好第 {r} 行的时段无法识别，已跳过。")
            continue
        result.update((member, d, h) for h in slots)
    return result


def is_effective_sheet_name(name: str) -> bool:
    return name == "有效时间矩阵" or name.endswith("_有效时间矩阵")


def workbook_paths(input_path: str | Path) -> List[Path]:
    p = Path(input_path).expanduser()
    if not p.exists():
        raise FileNotFoundError(f"找不到输入路径：{p}")
    if p.is_file():
        return [p]
    files = sorted(
        f for f in p.glob("*.xlsx")
        if not f.name.startswith("~$") and f.name != OUTPUT_XLSX_NAME
    )
    if not files:
        raise FileNotFoundError(f"文件夹 {p} 中没有可读取的 .xlsx 文件。")
    return files


def load_availability(input_path: str | Path) -> InputData:
    warnings: List[str] = []
    availability: Dict[str, Dict[date, List[int]]] = {}
    public_rules: Dict[date, List[int]] = {}
    soft_avoid: Set[Tuple[str, date, int]] = set()
    paths = workbook_paths(input_path)

    for path in paths:
        wb = load_workbook(path, data_only=True, read_only=False)
        effective_names = [name for name in wb.sheetnames if is_effective_sheet_name(name)]
        candidate_names = effective_names
        if not candidate_names:
            candidate_names = [
                name for name in wb.sheetnames
                if name not in {"公共限制", "排练偏好"} and find_matrix_header(wb[name])
            ]
            if candidate_names:
                warnings.append(f"{path.name} 没有‘有效时间矩阵’，已改读其中可识别的个人矩阵。")

        for name in candidate_names:
            ws = wb[name]
            member = extract_member_name(ws, name)
            if not member:
                warnings.append(f"{path.name}/{name} 无法识别成员姓名，已跳过。")
                continue
            matrix = read_matrix_sheet(ws, f"{path.name}/{name}", warnings)
            if member in availability and availability[member] != matrix:
                raise ValueError(f"成员 {member} 在多个文件/工作表中出现，且矩阵内容不一致。")
            availability[member] = matrix

        if "公共限制" in wb.sheetnames:
            rules = read_matrix_sheet(wb["公共限制"], f"{path.name}/公共限制", warnings)
            for d, row in rules.items():
                if d in public_rules and public_rules[d] != row:
                    raise ValueError(f"日期 {d} 的公共限制在多个文件中不一致。")
                public_rules[d] = row
        if "排练偏好" in wb.sheetnames:
            soft_avoid |= read_soft_preferences(wb["排练偏好"], warnings)

    if not availability:
        raise ValueError("没有读到任何成员的时间矩阵。请确认工作表包含‘日期’和 14 个小时列。")

    all_dates = sorted({d for matrix in availability.values() for d in matrix})
    dates = [d for d in all_dates if EARLIEST_REHEARSAL_DATE <= d <= LAST_REHEARSAL_DATE and d < PERFORMANCE_DATE]
    if not dates:
        raise ValueError("输入矩阵中没有位于正式排练区间内的日期。")

    global_allowed: Dict[date, List[int]] = {}
    for d in dates:
        transit = [1] * H
        if d.weekday() >= 5:  # 周六、周日必须在 00:00 前结束
            transit[-1] = 0
        if d in public_rules:
            transit = [a * b for a, b in zip(transit, public_rules[d])]
        global_allowed[d] = transit

    # 即使输入的是个人原始矩阵，也在这里统一套用公共末班车限制。
    for member, matrix in availability.items():
        for d in dates:
            if d not in matrix:
                warnings.append(f"成员 {member} 缺少 {d} 这一行，已按全天不可用处理。")
                matrix[d] = [0] * H
            matrix[d] = [a * b for a, b in zip(matrix[d], global_allowed[d])]

    loaded = set(availability)
    unknown_names = sorted(loaded - set(MEMBER_ORDER))
    if unknown_names:
        warnings.append("读到未在 14 人名单中的成员：" + "、".join(unknown_names))

    return InputData(
        availability=availability,
        global_allowed=global_allowed,
        soft_avoid=soft_avoid,
        dates=dates,
        warnings=list(dict.fromkeys(warnings)),
        source_files=[str(p) for p in paths],
    )


def get_input_path() -> str:
    if USE_GOOGLE_DRIVE:
        try:
            from google.colab import drive
        except ImportError as exc:
            raise RuntimeError("USE_GOOGLE_DRIVE=True 只能在 Google Colab 中使用。") from exc
        drive.mount("/content/drive")
        return GOOGLE_DRIVE_PATH
    if INPUT_PATH:
        return INPUT_PATH
    try:
        from google.colab import files
    except ImportError as exc:
        raise RuntimeError("本地运行时请先填写 INPUT_PATH。") from exc
    uploaded = files.upload()
    if not uploaded:
        raise RuntimeError("没有上传文件。")
    if len(uploaded) > 1:
        folder = Path("/content/上传的矩阵")
        folder.mkdir(exist_ok=True)
        for name, content in uploaded.items():
            (folder / name).write_bytes(content)
        return str(folder)
    return str(Path("/content") / next(iter(uploaded)))


# %% [markdown]
# ## 2. 建模与分层最优化
#

# %% [markdown]
# ## 2. 建模与分层最优化
#
# “全部排完”是硬目标；只有在它成立之后，才依次优化困难曲目日期、同曲间隔、
# 成员往返、当天空档、单日过长和 9 月 19 日。若的“可能加班”时段仅作为最后的
# 平局打破项，因此不会反过来破坏前面七级优先级。

# %%
def make_tasks(song_ids: Iterable[str]) -> List[Task]:
    tasks: List[Task] = []
    for song_id in sorted(song_ids):
        durations = SONG_SESSION_OVERRIDE.get(song_id, REQUIRED_DURATIONS[SONGS[song_id]["difficulty"]])
        for i, duration in enumerate(durations, start=1):
            tasks.append(Task(f"{song_id}_{i}", song_id, i, duration))
    return tasks


def split_active_songs(data: InputData) -> Tuple[List[str], List[dict]]:
    loaded = set(data.availability)
    active: List[str] = []
    pending: List[dict] = []
    for song_id, song in SONGS.items():
        missing = [m for m in song["members"] if m not in loaded]
        if missing:
            pending.append({
                "曲目ID": song_id,
                "曲目": song["name"],
                "难度": song["difficulty"],
                "全体成员": "、".join(song["members"]),
                "缺少时间表": "、".join(missing),
                "状态": "等待时间表",
            })
        else:
            active.append(song_id)
    if pending and MISSING_MEMBER_POLICY == "strict":
        missing_all = sorted({m for row in pending for m in row["缺少时间表"].split("、")}, key=lambda x: MEMBER_ORDER.index(x))
        raise ValueError("strict 模式：尚缺成员时间表：" + "、".join(missing_all))
    if MISSING_MEMBER_POLICY not in {"strict", "provisional"}:
        raise ValueError("MISSING_MEMBER_POLICY 只能是 'strict' 或 'provisional'。")
    return active, pending


def candidate_is_available(data: InputData, song_id: str, d: date, start: int, duration: int) -> bool:
    hours = range(start, start + duration)
    if not all(data.global_allowed[d][h] for h in hours):
        return False
    return all(
        all(data.availability[member][d][h] for h in hours)
        for member in SONGS[song_id]["members"]
    )


def build_candidate_lists(data: InputData, tasks: Sequence[Task], strict: bool = True) -> Dict[str, List[Candidate]]:
    result: Dict[str, List[Candidate]] = {}
    for task in tasks:
        choices: List[Candidate] = []
        for di, d in enumerate(data.dates):
            for start in range(0, H - task.duration + 1):
                if strict:
                    allowed = candidate_is_available(data, task.song_id, d, start, task.duration)
                else:
                    allowed = all(data.global_allowed[d][h] for h in range(start, start + task.duration))
                if allowed:
                    choices.append(Candidate(di, start, task.duration))
                elif strict:
                    # 近似解：允许恰好缺席一名成员（全局时间必须满足）
                    global_ok = all(data.global_allowed[d][h] for h in range(start, start + task.duration))
                    if global_ok:
                        for absent_m in SONGS[task.song_id]["members"]:
                            other_m = [m for m in SONGS[task.song_id]["members"] if m != absent_m]
                            if other_m and all(
                                data.availability[m][d][h]
                                for m in other_m
                                if m in data.availability and d in data.availability[m]
                                for h in range(start, start + task.duration)
                            ):
                                choices.append(Candidate(di, start, task.duration, absent_m))
        result[task.task_id] = choices
    return result


def candidate_count_rows(tasks: Sequence[Task], candidates: Mapping[str, Sequence[Candidate]]) -> List[dict]:
    rows = []
    for task in tasks:
        dates = {c.date_idx for c in candidates[task.task_id]}
        rows.append({
            "任务ID": task.task_id,
            "曲目ID": task.song_id,
            "曲目": SONGS[task.song_id]["name"],
            "难度": SONGS[task.song_id]["difficulty"],
            "时长(小时)": task.duration,
            "候选连续时段数": len(candidates[task.task_id]),
            "覆盖日期数": len(dates),
            "状态": "可建模" if candidates[task.task_id] else "无共同连续时段",
        })
    return rows


@dataclass
class ModelBundle:
    model: cp_model.CpModel
    tasks: List[Task]
    candidates: Dict[str, List[Candidate]]
    x: Dict[Tuple[str, int], cp_model.IntVar]
    day_vars: Dict[str, cp_model.IntVar]
    start_abs_vars: Dict[str, cp_model.IntVar]
    occupancy: Dict[Tuple[str, int, int], cp_model.IntVar]
    objectives: Dict[str, Tuple[object, int]]


def build_complete_model(data: InputData, tasks: Sequence[Task], candidates: Dict[str, List[Candidate]], *, windows_919=None, max_absent_ratio: float = 0.20) -> ModelBundle:
    zero = [task.task_id for task in tasks if not candidates[task.task_id]]
    if zero:
        raise ValueError("以下任务没有任何共同连续时段：" + "、".join(zero))

    model = cp_model.CpModel()
    x: Dict[Tuple[str, int], cp_model.IntVar] = {}
    day_vars: Dict[str, cp_model.IntVar] = {}
    start_abs_vars: Dict[str, cp_model.IntVar] = {}
    task_by_id = {task.task_id: task for task in tasks}

    for task in tasks:
        vars_for_task = []
        for ci, _ in enumerate(candidates[task.task_id]):
            var = model.NewBoolVar(f"x_{task.task_id}_{ci}")
            x[(task.task_id, ci)] = var
            vars_for_task.append(var)
        model.Add(sum(vars_for_task) == 1)

        day_var = model.NewIntVar(0, len(data.dates) - 1, f"day_{task.task_id}")
        start_abs = model.NewIntVar(0, len(data.dates) * H - 1, f"startabs_{task.task_id}")
        model.Add(day_var == sum(c.date_idx * x[(task.task_id, ci)] for ci, c in enumerate(candidates[task.task_id])))
        model.Add(start_abs == sum((c.date_idx * H + c.start) * x[(task.task_id, ci)] for ci, c in enumerate(candidates[task.task_id])))
        day_vars[task.task_id] = day_var
        start_abs_vars[task.task_id] = start_abs

    # 相同曲目、相同时长的任务完全对称；固定顺序只用于减少搜索，不改变可行解集合。
    symmetry_groups: Dict[Tuple[str, int], List[Task]] = defaultdict(list)
    for task in tasks:
        symmetry_groups[(task.song_id, task.duration)].append(task)
    for group in symmetry_groups.values():
        group = sorted(group, key=lambda t: t.requirement_no)
        for left, right in zip(group, group[1:]):
            model.Add(start_abs_vars[left.task_id] < start_abs_vars[right.task_id])

    cover: Dict[Tuple[str, int, int], List[cp_model.IntVar]] = defaultdict(list)
    for task in tasks:
        members = SONGS[task.song_id]["members"]
        for ci, c in enumerate(candidates[task.task_id]):
            var = x[(task.task_id, ci)]
            for member in members:
                for h in c.hours:
                    cover[(member, c.date_idx, h)].append(var)

    active_members = sorted(
        {member for task in tasks for member in SONGS[task.song_id]["members"]},
        key=lambda m: MEMBER_ORDER.index(m) if m in MEMBER_ORDER else 999,
    )
    occupancy: Dict[Tuple[str, int, int], cp_model.IntVar] = {}
    trip_terms: List[cp_model.IntVar] = []
    gap_terms: List[cp_model.IntVar] = []
    overtime_terms: List[cp_model.IntVar] = []

    for member in active_members:
        for di, _d in enumerate(data.dates):
            ys: List[cp_model.IntVar] = []
            for h in range(H):
                y = model.NewBoolVar(f"busy_{member}_{di}_{h}")
                relevant = cover.get((member, di, h), [])
                if relevant:
                    model.Add(sum(relevant) <= 1)  # H4：同一成员不能重叠排练
                    model.Add(y == sum(relevant))
                else:
                    model.Add(y == 0)
                occupancy[(member, di, h)] = y
                ys.append(y)

            daily_hours = model.NewIntVar(0, H, f"hours_{member}_{di}")
            model.Add(daily_hours == sum(ys))
            model.Add(daily_hours <= HARD_DAILY_HOUR_LIMIT)
            day_active = model.NewBoolVar(f"active_{member}_{di}")
            model.AddMaxEquality(day_active, ys)

            # 访问段：若当前忙、且前面 MERGE_VISIT_GAP_HOURS+1 个小时均不忙，则算一次新到场。
            visit_starts: List[cp_model.IntVar] = []
            lookback = MERGE_VISIT_GAP_HOURS + 1
            for h, y in enumerate(ys):
                start_visit = model.NewBoolVar(f"visit_{member}_{di}_{h}")
                previous = ys[max(0, h - lookback):h]
                model.Add(start_visit <= y)
                if not previous:
                    model.Add(start_visit == y)
                else:
                    for prev in previous:
                        model.Add(start_visit <= 1 - prev)
                    model.Add(start_visit >= y - sum(previous))
                visit_starts.append(start_visit)
            visit_blocks = model.NewIntVar(0, H, f"visitblocks_{member}_{di}")
            model.Add(visit_blocks == sum(visit_starts))
            extra_trips = model.NewIntVar(0, H, f"extratrips_{member}_{di}")
            model.Add(extra_trips == visit_blocks - day_active)
            trip_terms.append(extra_trips)

            # 当天总空档 = 最晚结束 - 最早开始 - 实际排练小时。
            first_candidates = []
            last_candidates = []
            for h, y in enumerate(ys):
                first_tmp = model.NewIntVar(0, H, f"firsttmp_{member}_{di}_{h}")
                model.Add(first_tmp == h).OnlyEnforceIf(y)
                model.Add(first_tmp == H).OnlyEnforceIf(y.Not())
                first_candidates.append(first_tmp)
                last_tmp = model.NewIntVar(0, H, f"lasttmp_{member}_{di}_{h}")
                model.Add(last_tmp == h + 1).OnlyEnforceIf(y)
                model.Add(last_tmp == 0).OnlyEnforceIf(y.Not())
                last_candidates.append(last_tmp)
            first_start = model.NewIntVar(0, H, f"first_{member}_{di}")
            last_end = model.NewIntVar(0, H, f"last_{member}_{di}")
            model.AddMinEquality(first_start, first_candidates)
            model.AddMaxEquality(last_end, last_candidates)
            gap = model.NewIntVar(0, H, f"gap_{member}_{di}")
            model.Add(gap == last_end - first_start - daily_hours).OnlyEnforceIf(day_active)
            model.Add(gap == 0).OnlyEnforceIf(day_active.Not())
            excess_gap = model.NewIntVar(0, H, f"excessgap_{member}_{di}")
            model.AddMaxEquality(excess_gap, [gap - FREE_GAP_HOURS, 0])
            gap_terms.append(excess_gap)

            overtime = model.NewIntVar(0, H, f"overtime_{member}_{di}")
            model.AddMaxEquality(overtime, [daily_hours - SOFT_DAILY_HOUR_LIMIT, 0])
            overtime_terms.append(overtime)

    # ── 硬约束：9.19 最多只允许一首曲目 ──
    last_date_idx = next(
        (i for i, d in enumerate(data.dates) if d == LAST_REHEARSAL_DATE), None
    )
    if last_date_idx is not None:
        song_on_last_day = {}
        for song_id in sorted({task.song_id for task in tasks}):
            vars_on_last = [
                x[(task.task_id, ci)]
                for task in tasks if task.song_id == song_id
                for ci, c in enumerate(candidates[task.task_id])
                if c.date_idx == last_date_idx
            ]
            if vars_on_last:
                on_last = model.NewBoolVar(f"on_last_{song_id}")
                model.AddMaxEquality(on_last, vars_on_last)
                song_on_last_day[song_id] = on_last
        if song_on_last_day:
            model.Add(sum(song_on_last_day.values()) <= 1)

        # ── 特殊：集中菁的排练天数（减少远途通勤）──
    FOCUS_MEMBER = "菁"
    focus_day_terms: List[cp_model.IntVar] = []
    if FOCUS_MEMBER in active_members:
        for di in range(len(data.dates)):
            focus_hours = [
                occupancy[(FOCUS_MEMBER, di, h)]
                for h in range(H)
                if (FOCUS_MEMBER, di, h) in occupancy
            ]
            if focus_hours:
                day_flag = model.NewBoolVar(f"focus_day_{di}")
                model.AddMaxEquality(day_flag, focus_hours)
                focus_day_terms.append(day_flag)
    else:
        focus_day_terms = []

        # F2：困难曲目先完成；先压低最晚一次日期，再压低其余日期。
    hard_early_terms: List[object] = []
    for song_id in sorted({task.song_id for task in tasks}):
        if SONGS[song_id]["difficulty"] != "困难":
            continue
        song_days = [day_vars[t.task_id] for t in tasks if t.song_id == song_id]
        completion_day = model.NewIntVar(0, len(data.dates) - 1, f"hardcomplete_{song_id}")
        model.AddMaxEquality(completion_day, song_days)
        hard_early_terms.append(100 * completion_day + sum(song_days))

    # F3：同曲同日重罚；日期差少于 2 天时按缺少天数处罚。
    # ── 硬约束：9.19 时间窗口约束（由 windows_919 参数控制）──────────
    import datetime as _dt
    _date_919 = _dt.date(2026, 9, 19)
    # windows_919: [(start_idx, end_idx), ...]，落入任一窗口即允许
    # idx映射: 5=16:00, 7=18:00, 9=20:00, 11=22:00, 13=0:00(24:00)
    _w919 = windows_919 if windows_919 is not None else [(5, 9)]
    if _date_919 in data.dates:
        _idx_919 = data.dates.index(_date_919)
        def _in_w919(cand):
            return any(cand.start >= ws and cand.start + cand.duration <= we
                       for ws, we in _w919)
        _on_919_banned = [
            x[(t.task_id, ci)]
            for t in tasks
            for ci, cand in enumerate(candidates[t.task_id])
            if cand.date_idx == _idx_919 and not _in_w919(cand)
        ]
        if _on_919_banned:
            model.Add(sum(_on_919_banned) == 0)
        _on_919_allowed = [
            x[(t.task_id, ci)]
            for t in tasks
            for ci, cand in enumerate(candidates[t.task_id])
            if cand.date_idx == _idx_919 and _in_w919(cand)
        ]
        if _on_919_allowed:
            model.Add(sum(_on_919_allowed) <= 1)

    # ── 预处理：按曲目分组任务 ──────────────────────────────────────
    tasks_by_song: Dict[str, List[Task]] = {}
    for _t in tasks:
        tasks_by_song.setdefault(_t.song_id, []).append(_t)

    # ── [已移除] 近似解约束（改为软目标，避免在新时间表下无解）──────
    # 每首歌每位成员最多缺席1次的约束已移至软目标层，
    # 由目标函数1b（最小化缺席次数）来尽量优化，而非强制。

    # ── 硬约束：每首歌至少有一次排练必须全员到齐 ────────────────────
    for _s2id, _s2tasks in tasks_by_song.items():
        _full_vars = [
            x[(t.task_id, ci)]
            for t in _s2tasks
            for ci, cand in enumerate(candidates[t.task_id])
            if cand.absent_member == ""
        ]
        if _full_vars:
            model.Add(sum(_full_vars) >= 1)

    spacing_terms: List[cp_model.IntVar] = []
    for song_id, song_tasks in tasks_by_song.items():
        for i in range(len(song_tasks)):
            for j in range(i + 1, len(song_tasks)):
                left, right = song_tasks[i], song_tasks[j]
                # 硬约束：同曲不同天
                model.AddAllDifferent([day_vars[left.task_id], day_vars[right.task_id]])
                raw_diff = model.NewIntVar(-(len(data.dates)-1), len(data.dates)-1, f"rawdiff_{left.task_id}_{right.task_id}")
                model.Add(raw_diff == day_vars[left.task_id] - day_vars[right.task_id])
                diff = model.NewIntVar(0, len(data.dates) - 1, f"datediff_{left.task_id}_{right.task_id}")
                model.AddAbsEquality(diff, raw_diff)
                same_day = model.NewBoolVar(f"sameday_{left.task_id}_{right.task_id}")
                model.Add(diff == 0).OnlyEnforceIf(same_day)
                model.Add(diff >= 1).OnlyEnforceIf(same_day.Not())
                shortfall = model.NewIntVar(0, 2, f"space_shortfall_{left.task_id}_{right.task_id}")
                model.AddMaxEquality(shortfall, [2 - diff, 0])
                spacing_terms.append(100 * same_day + shortfall)

    # ── 硬约束：菁 在 aespa-lemonadeB(e) 只参加1次排练 ─────────
    _jing_lemonade_present = [
        x[(t.task_id, ci)]
        for t in tasks if t.song_id == 'e'
        for ci, cand in enumerate(candidates[t.task_id])
        if cand.absent_member != '菁'
    ]
    if _jing_lemonade_present:
        model.Add(sum(_jing_lemonade_present) == 1)

    # F7：9 月 19 日尽量不排正式训练。
    last_day_terms: List[cp_model.IntVar] = []
    for task in tasks:
        for ci, c in enumerate(candidates[task.task_id]):
            if data.dates[c.date_idx] == LAST_REHEARSAL_DATE:
                last_day_terms.append(x[(task.task_id, ci)])

    # 额外软偏好只作最终平局打破项，不改变 F1-F7 的顺序。
    soft_avoid_terms: List[object] = []
    for task in tasks:
        members = SONGS[task.song_id]["members"]
        for ci, c in enumerate(candidates[task.task_id]):
            d = data.dates[c.date_idx]
            penalty = sum((member, d, h) in data.soft_avoid for member in members for h in c.hours)
            if penalty:
                soft_avoid_terms.append(penalty * x[(task.task_id, ci)])

    # 计算缺席项（用于最小化缺席目标）
    _absence_terms = [
        x[(t.task_id, ci)]
        for t in tasks
        for ci, cand in enumerate(candidates[t.task_id])
        if cand.absent_member
    ]
    # ── 硬约束：全员参加率（由 max_absent_ratio 参数控制）──────────────
    _max_absent_sessions = max(0, int(len(tasks) * max_absent_ratio))
    if _absence_terms:
        model.Add(sum(_absence_terms) <= _max_absent_sessions)


    objectives = {
        "1b_最小化缺席次数_优先全员参与": (100 * sum(_absence_terms) if _absence_terms else model.NewConstant(0), max(len(_absence_terms), 1)),
        "3b_集中菁的排练天数_减少通勤": (sum(focus_day_terms), len(focus_day_terms)),
        "4_减少成员额外往返": (sum(trip_terms), len(trip_terms)),
        "5_减少成员当天长空档": (sum(gap_terms), len(gap_terms)),
        "8_避开成员软约束时段_平局项": (sum(soft_avoid_terms), len(soft_avoid_terms)),
    }
    return ModelBundle(model, list(tasks), candidates, x, day_vars, start_abs_vars, occupancy, objectives)


@dataclass
class SolveResult:
    feasible: bool
    exact_lexicographic_optimum: bool
    solver: Optional[cp_model.CpSolver]
    status: str
    stage_records: List[dict]


def new_solver(time_limit: float = SOLVER_TIME_LIMIT_PER_STAGE) -> cp_model.CpSolver:
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = float(time_limit)
    solver.parameters.num_search_workers = int(SOLVER_WORKERS)
    solver.parameters.random_seed = int(RANDOM_SEED)
    solver.parameters.log_search_progress = False
    return solver


def solve_lexicographically(bundle: ModelBundle) -> SolveResult:
    model = bundle.model
    records: List[dict] = []
    exact = True

    # F1：任务都已用 ==1 约束；先只验证全部能排完。
    model.Minimize(0)
    solver = new_solver()
    status = solver.Solve(model)
    status_name = solver.StatusName(status)
    if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return SolveResult(False, False, None, status_name, [{"优先级": "1_确保全部排练完成", "目标值": None, "状态": status_name}])
    exact &= status == cp_model.OPTIMAL
    records.append({"优先级": "1_确保全部排练完成", "目标值": 0, "状态": status_name})
    last_feasible_solver = solver

    for stage_name, (expr, component_count) in bundle.objectives.items():
        if component_count == 0:
            records.append({"优先级": stage_name, "目标值": 0, "状态": "无适用项"})
            continue
        model.Minimize(expr)
        stage_solver = new_solver()
        stage_status = stage_solver.Solve(model)
        stage_status_name = stage_solver.StatusName(stage_status)
        if stage_status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            records.append({"优先级": stage_name, "目标值": None, "状态": stage_status_name})
            exact = False
            break
        optimum = int(round(stage_solver.ObjectiveValue()))
        records.append({"优先级": stage_name, "目标值": optimum, "状态": stage_status_name})
        if stage_status != cp_model.OPTIMAL:
            exact = False
        # 固定上一层最佳值，再进入下一层，保证真正的字典序优先级。
        model.Add(expr == optimum)
        last_feasible_solver = stage_solver

    return SolveResult(True, exact, last_feasible_solver, last_feasible_solver.StatusName(), records)


def time_text(start: int, duration: int) -> Tuple[str, str, str]:
    start_text = f"{BOUNDARY_HOURS[start]:02d}:00"
    end_text = f"{BOUNDARY_HOURS[start + duration]:02d}:00"
    return start_text, end_text, f"{start_text}–{end_text}"


def extract_schedule(data: InputData, bundle: ModelBundle, solver: cp_model.CpSolver) -> List[dict]:
    selected = []
    task_by_id = {task.task_id: task for task in bundle.tasks}
    for task in bundle.tasks:
        for ci, c in enumerate(bundle.candidates[task.task_id]):
            if solver.Value(bundle.x[(task.task_id, ci)]) == 1:
                d = data.dates[c.date_idx]
                start_text, end_text, block = time_text(c.start, c.duration)
                selected.append({
                    "_task_id": task.task_id,
                    "_slot_start": c.start,
                    "曲目ID": task.song_id,
                    "曲目": SONGS[task.song_id]["name"],
                    "难度": SONGS[task.song_id]["difficulty"],
                    "日期": d,
                    "星期": WEEKDAY_ZH[d.weekday()],
                    "开始": start_text,
                    "结束": end_text,
                    "时间段": block,
                    "时长(小时)": c.duration,
                    "成员": "、".join(SONGS[task.song_id]["members"]),
                    "缺席": c.absent_member if c.absent_member else "全员到齐",
                    "9月19日": "是" if d == LAST_REHEARSAL_DATE else "否",
                    "软约束命中小时": sum(
                        (member, d, h) in data.soft_avoid
                        for member in SONGS[task.song_id]["members"] for h in c.hours
                    ),
                })
                break
    selected.sort(key=lambda r: (r["日期"], int(r["开始"].split(":")[0]) if int(r["开始"].split(":")[0]) >= 11 else int(r["开始"].split(":")[0]) + 24, r["曲目ID"]))
    occurrence = defaultdict(int)
    for row in selected:
        occurrence[row["曲目ID"]] += 1
        row["同曲第几次"] = occurrence[row["曲目ID"]]
        row.pop("_task_id", None)
    return selected

# %% [markdown]
# ## 3. 无解诊断
#
# 诊断分四层：无候选任务、最大可排次数、只差一名成员的时段、全局最小开放时间。

# %%
def add_partial_hard_constraints(
    model: cp_model.CpModel,
    data: InputData,
    tasks: Sequence[Task],
    candidates: Mapping[str, Sequence[Candidate]],
    x: Mapping[Tuple[str, int], cp_model.IntVar],
) -> None:
    cover: Dict[Tuple[str, int, int], List[cp_model.IntVar]] = defaultdict(list)
    for task in tasks:
        for ci, c in enumerate(candidates[task.task_id]):
            var = x[(task.task_id, ci)]
            for member in SONGS[task.song_id]["members"]:
                for h in c.hours:
                    cover[(member, c.date_idx, h)].append(var)

    members = {m for task in tasks for m in SONGS[task.song_id]["members"]}
    for member in members:
        for di, _ in enumerate(data.dates):
            hourly_exprs = []
            for h in range(H):
                relevant = cover.get((member, di, h), [])
                if relevant:
                    model.Add(sum(relevant) <= 1)
                    hourly_exprs.append(sum(relevant))
            if hourly_exprs:
                model.Add(sum(hourly_exprs) <= HARD_DAILY_HOUR_LIMIT)


def solve_maximum_coverage(
    data: InputData,
    tasks: Sequence[Task],
    candidates: Dict[str, List[Candidate]],
    time_limit: float = 45.0,
) -> Tuple[int, Dict[str, int], str]:
    model = cp_model.CpModel()
    x: Dict[Tuple[str, int], cp_model.IntVar] = {}
    scheduled: Dict[str, cp_model.IntVar] = {}
    for task in tasks:
        vars_for_task = []
        for ci, _ in enumerate(candidates[task.task_id]):
            var = model.NewBoolVar(f"cover_x_{task.task_id}_{ci}")
            x[(task.task_id, ci)] = var
            vars_for_task.append(var)
        is_scheduled = model.NewBoolVar(f"scheduled_{task.task_id}")
        scheduled[task.task_id] = is_scheduled
        if vars_for_task:
            model.Add(sum(vars_for_task) == is_scheduled)
        else:
            model.Add(is_scheduled == 0)

    add_partial_hard_constraints(model, data, tasks, candidates, x)
    difficulty_tie = {"困难": 3, "一般": 2, "简单": 1}
    count_expr = sum(scheduled.values())
    tie_expr = sum(difficulty_tie[SONGS[t.song_id]["difficulty"]] * scheduled[t.task_id] for t in tasks)
    model.Maximize(1000 * count_expr + tie_expr)
    solver = new_solver(time_limit)
    status = solver.Solve(model)
    if status not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return 0, {}, solver.StatusName(status)
    counts = defaultdict(int)
    for task in tasks:
        counts[task.song_id] += solver.Value(scheduled[task.task_id])
    return sum(counts.values()), dict(counts), solver.StatusName(status)


def independent_song_maximum(data: InputData, song_id: str) -> int:
    tasks = make_tasks([song_id])
    candidates = build_candidate_lists(data, tasks, strict=True)
    total, _, _ = solve_maximum_coverage(data, tasks, candidates, time_limit=15.0)
    return total


def missing_session_rows(
    data: InputData,
    active_song_ids: Sequence[str],
    global_counts: Optional[Dict[str, int]] = None,
) -> List[dict]:
    global_counts = global_counts or {}
    rows = []
    for song_id in active_song_ids:
        required = len(REQUIRED_DURATIONS[SONGS[song_id]["difficulty"]])
        independent_max = independent_song_maximum(data, song_id)
        global_count = global_counts.get(song_id, 0)
        rows.append({
            "曲目ID": song_id,
            "曲目": SONGS[song_id]["name"],
            "难度": SONGS[song_id]["difficulty"],
            "要求次数": required,
            "该曲目单独最多可排": independent_max,
            "单曲仍缺次数": required - independent_max,
            "全局最大覆盖方案已排": global_count,
            "全局方案仍缺次数": required - global_count,
        })
    return rows


def blocking_members_for_block(data: InputData, song_id: str, d: date, start: int, duration: int) -> Dict[str, List[int]]:
    blockers: Dict[str, List[int]] = {}
    for member in SONGS[song_id]["members"]:
        missing = [h for h in range(start, start + duration) if data.availability[member][d][h] == 0]
        if missing:
            blockers[member] = missing
    return blockers


def near_miss_rows(data: InputData, active_song_ids: Sequence[str], limit: int = 250) -> List[dict]:
    rows: List[dict] = []
    for song_id in active_song_ids:
        durations = sorted(set(REQUIRED_DURATIONS[SONGS[song_id]["difficulty"]]), reverse=True)
        for duration in durations:
            for di, d in enumerate(data.dates):
                for start in range(0, H - duration + 1):
                    if not all(data.global_allowed[d][h] for h in range(start, start + duration)):
                        continue
                    blockers = blocking_members_for_block(data, song_id, d, start, duration)
                    if len(blockers) != 1:
                        continue
                    member, hours = next(iter(blockers.items()))
                    start_text, end_text, block = time_text(start, duration)
                    rows.append({
                        "曲目ID": song_id,
                        "曲目": SONGS[song_id]["name"],
                        "时长(小时)": duration,
                        "日期": d,
                        "星期": WEEKDAY_ZH[d.weekday()],
                        "候选时段": block,
                        "只差成员": member,
                        "需额外开放小时数": len(hours),
                        "需开放的小时格": "、".join(SLOT_LABELS[h] for h in hours),
                    })
    rows.sort(key=lambda r: (r["需额外开放小时数"], r["日期"], r["曲目ID"], r["候选时段"]))
    return rows[:limit]


@dataclass
class AdjustmentResult:
    feasible: bool
    status: str
    exact: bool
    affected_members: int
    changed_hours: int
    changes: List[dict]
    relaxed_schedule: List[dict]


def solve_minimum_adjustment(data: InputData, tasks: Sequence[Task], time_limit: float = 60.0) -> AdjustmentResult:
    # 允许使用个人矩阵中原本为 0 的格子，但仍遵守公共末班车、人员不重叠和单日硬上限。
    candidates = build_candidate_lists(data, tasks, strict=False)
    if any(not candidates[t.task_id] for t in tasks):
        return AdjustmentResult(False, "公共时间范围本身不足", False, 0, 0, [], [])

    model = cp_model.CpModel()
    x: Dict[Tuple[str, int], cp_model.IntVar] = {}
    change: Dict[Tuple[str, int, int], cp_model.IntVar] = {}
    for task in tasks:
        vars_for_task = []
        for ci, c in enumerate(candidates[task.task_id]):
            var = model.NewBoolVar(f"relax_x_{task.task_id}_{ci}")
            x[(task.task_id, ci)] = var
            vars_for_task.append(var)
            d = data.dates[c.date_idx]
            for member in SONGS[task.song_id]["members"]:
                for h in c.hours:
                    if data.availability[member][d][h] == 0:
                        key = (member, c.date_idx, h)
                        if key not in change:
                            change[key] = model.NewBoolVar(f"open_{member}_{c.date_idx}_{h}")
                        model.Add(var <= change[key])
        model.Add(sum(vars_for_task) == 1)

    add_partial_hard_constraints(model, data, tasks, candidates, x)
    member_changes: Dict[str, List[cp_model.IntVar]] = defaultdict(list)
    for (member, _di, _h), var in change.items():
        member_changes[member].append(var)
    affected: Dict[str, cp_model.IntVar] = {}
    for member, vars_for_member in member_changes.items():
        flag = model.NewBoolVar(f"affected_{member}")
        model.AddMaxEquality(flag, vars_for_member)
        affected[member] = flag

    affected_expr = sum(affected.values())
    changed_expr = sum(change.values())
    model.Minimize(affected_expr)
    solver1 = new_solver(time_limit)
    status1 = solver1.Solve(model)
    if status1 not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return AdjustmentResult(False, solver1.StatusName(status1), False, 0, 0, [], [])
    best_affected = int(round(solver1.ObjectiveValue()))
    model.Add(affected_expr == best_affected)

    model.Minimize(changed_expr)
    solver2 = new_solver(time_limit)
    status2 = solver2.Solve(model)
    if status2 not in (cp_model.OPTIMAL, cp_model.FEASIBLE):
        return AdjustmentResult(False, solver2.StatusName(status2), False, 0, 0, [], [])
    best_changed = int(round(solver2.ObjectiveValue()))
    exact = status1 == cp_model.OPTIMAL and status2 == cp_model.OPTIMAL

    changes = []
    for (member, di, h), var in change.items():
        if solver2.Value(var):
            d = data.dates[di]
            changes.append({
                "成员": member,
                "日期": d,
                "星期": WEEKDAY_ZH[d.weekday()],
                "需额外开放小时格": SLOT_LABELS[h],
                "调整小时数": 1,
            })
    changes.sort(key=lambda r: (MEMBER_ORDER.index(r["成员"]) if r["成员"] in MEMBER_ORDER else 999, r["日期"], r["需额外开放小时格"]))

    relaxed_schedule = []
    for task in tasks:
        for ci, c in enumerate(candidates[task.task_id]):
            if solver2.Value(x[(task.task_id, ci)]):
                d = data.dates[c.date_idx]
                _, _, block = time_text(c.start, c.duration)
                relaxed_schedule.append({
                    "任务ID": task.task_id,
                    "曲目ID": task.song_id,
                    "曲目": SONGS[task.song_id]["name"],
                    "日期": d,
                    "星期": WEEKDAY_ZH[d.weekday()],
                    "建议时段": block,
                    "时长(小时)": c.duration,
                    "成员": "、".join(SONGS[task.song_id]["members"]),
                })
                break
    relaxed_schedule.sort(key=lambda r: (r["日期"], r["建议时段"], r["曲目ID"]))
    return AdjustmentResult(True, solver2.StatusName(status2), exact, best_affected, best_changed, changes, relaxed_schedule)


def member_schedule_rows(schedule: Sequence[dict]) -> List[dict]:
    rows = []
    for session in schedule:
        for member in SONGS[session["曲目ID"]]["members"]:
            rows.append({
                "成员": member,
                "日期": session["日期"],
                "星期": session["星期"],
                "时间段": session["时间段"],
                "曲目ID": session["曲目ID"],
                "曲目": session["曲目"],
                "时长(小时)": session["时长(小时)"],
            })
    rows.sort(key=lambda r: (MEMBER_ORDER.index(r["成员"]) if r["成员"] in MEMBER_ORDER else 999, r["日期"], r["时间段"]))
    return rows

# ===== 主执行入口 =====
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Step 1: 读取输入
# ── 上传时间表文件 ──────────────────────────────────────────
from google.colab import files as _colab_files
print("📂 请选择时间表 xlsx 文件上传：")
_uploaded = _colab_files.upload()
if not _uploaded:
    raise ValueError("未上传文件，已中止。")
INPUT_PATH = "/content/" + list(_uploaded.keys())[0]
print(f"✅ 已上传：{INPUT_PATH}")
input_path = get_input_path()
data = load_availability(input_path)

for w in data.warnings:
    print("⚠️", w)

# Step 2: 拆分有效曲目 / 待补曲目
active_songs, pending_songs = split_active_songs(data)
print(f"\n✅ 可排曲目（{len(active_songs)} 首）：{', '.join(active_songs)}")
if pending_songs:
    print(f"⏳ 待补成员（{len(pending_songs)} 首）：{', '.join(pending_songs)}")

# Step 3: 建模求解
tasks = make_tasks(active_songs)
candidates = build_candidate_lists(data, tasks, strict=True)
# ── 级联尝试：依次放宽 9.19 时间窗口和全员率约束 ──────────────────
_ATTEMPTS = [
    {
        "desc": "尝试1：9.19 只排 18:00-20:00，全员率≥80%",
        "windows_919": [(7, 9)],
        "max_absent_ratio": 0.20,
    },
    {
        "desc": "尝试2：9.19 加开 16:00-18:00（即16:00-20:00），全员率≥80%",
        "windows_919": [(5, 9)],
        "max_absent_ratio": 0.20,
    },
    {
        "desc": "尝试3：9.19 16:00-20:00，全员率放宽至≥75%",
        "windows_919": [(5, 9)],
        "max_absent_ratio": 0.25,
    },
]

result = None
bundle = None
for _attempt in _ATTEMPTS:
    print(f"\n{'='*60}")
    print(f"  {_attempt['desc']}")
    print(f"{'='*60}")
    bundle = build_complete_model(
        data, tasks, candidates,
        windows_919=_attempt["windows_919"],
        max_absent_ratio=_attempt["max_absent_ratio"],
    )
    result = solve_lexicographically(bundle)
    print("\n📊 分层求解过程：")
    for r in result.stage_records:
        print(f"  {r['优先级']}: 目标值={r['目标值']} 状态={r['状态']}")
    if result.feasible:
        print(f"✅ 可行！采用：{_attempt['desc']}")
        break
    else:
        print("❌ 无可行解，尝试下一配置...")

# Step 4: 输出
if result.feasible:
    print(f"  ✅ solver={type(result.solver).__name__}, status={result.status}")
    if result.solver is None:
        raise RuntimeError(f"❌ solver 为 None (status={result.status}) — 请检查 solve_lexicographically 函数")
    _schedule_rows = extract_schedule(data, bundle, result.solver)
    df = pd.DataFrame(_schedule_rows)
    display_cols = ["曲目ID","曲目","日期","星期","开始","结束","时长(小时)","缺席","成员"]
    df_disp = df[[c for c in display_cols if c in df.columns]]
    df_disp = df_disp.sort_values(["日期","开始"]).reset_index(drop=True)
    print(f"\n📅 排练时间表（共 {len(df_disp)} 场）")
    print(df_disp.to_string(index=False))
    out_path = OUTPUT_DIR / "最终时间表.xlsx"
    df_disp.to_excel(out_path, index=False)
    print(f"\n💾 已保存到 {out_path}")
else:
    print("❌ 无可行解，开始诊断...\n")
    _schedule_rows = []

    # ── 诊断1：各任务候选时段数 ────────────────────────────────
    print("=== 各任务候选时段数 ===")
    _tasks_d = make_tasks(active_songs)
    _cands_d = build_candidate_lists(data, _tasks_d, strict=True)
    for _t in _tasks_d:
        _full = sum(1 for c in _cands_d[_t.task_id] if not c.absent_member)
        _part = sum(1 for c in _cands_d[_t.task_id] if c.absent_member)
        _mark = "❌" if not _cands_d[_t.task_id] else ("⚠️" if _full == 0 else "✅")
        print(f"  {_mark} {_t.task_id}: 共{len(_cands_d[_t.task_id])}个候选 (全员{_full}/缺1人{_part})")

    # ── 诊断2：最大覆盖（放宽冲突约束，找哪些歌排不下）─────────
    print("\n=== 最大覆盖求解 ===")
    _total, _counts, _mstatus = solve_maximum_coverage(data, _tasks_d, _cands_d)
    for _sid in active_songs:
        _req = len(SONG_SESSION_OVERRIDE.get(_sid, REQUIRED_DURATIONS[SONGS[_sid]["difficulty"]]))
        _got = _counts.get(_sid, 0)
        _mark = "✅" if _got >= _req else "❌"
        print(f"  {_mark} {_sid}({SONGS[_sid]['name']}): 需{_req}场，最多能排{_got}场")

    # ── 诊断3：9.19 窗口内候选数 ──────────────────────────────
    import datetime as _dt2
    _d919 = _dt2.date(2026, 9, 19)
    if _d919 in data.dates:
        _idx919 = data.dates.index(_d919)
        _SLOT_14, _SLOT_20 = 3, 9
        _on919_all = [(t.task_id, c) for t in _tasks_d for c in _cands_d[t.task_id] if c.date_idx == _idx919]
        _on919_win = [(tid, c) for tid, c in _on919_all if c.start >= _SLOT_14 and c.start + c.duration <= _SLOT_20]
        print(f"\n=== 9.19 候选 ===")
        print(f"  全天候选数：{len(_on919_all)}")
        print(f"  14:00–20:00 窗口内：{len(_on919_win)} 个")
        for tid, c in _on919_win:
            print(f"    {tid} slot{c.start}~{c.start+c.duration} 缺:{c.absent_member or '无'}")

    # ── 诊断4：只差一人的近似可行时段 ─────────────────────────
    print("\n=== 近似可行（只差1人）- 前10条 ===")
    _nm = near_miss_rows(data, active_songs, limit=10)
    for r in _nm:
        print(f"  {r['曲目ID']} {r['日期']} {r['候选时段']} 只差：{r['只差成员']}")

# ===== 排程正确性验证 =====
import datetime as _dt_mod

_errors = []
_warnings = []
_checks = []

def _ok(msg):
    _checks.append(f"  ✅ {msg}")

def _fail(msg):
    _errors.append(f"  ❌ {msg}")

def _warn(msg):
    _warnings.append(f"  ⚠️  {msg}")

# 从 solve result 里取排程行
if result is None or not result.feasible or result.solver is None:
    print("⚠️ 无可行解或 solver 为 None，跳过验证。")
    raise SystemExit(0)
_rows = extract_schedule(data, bundle, result.solver)

print("=" * 60)
print("🔍 排程正确性验证报告")
print("=" * 60)


# ── 1. 全局时间段合法性 ──────────────────────────────────────
print("\n[1] 全局允许时间段检验")
for row in _rows:
    d = row["日期"]
    slot = row.get("_slot_start", SLOT_START_HOURS.index(int(row["开始"].split(":")[0])))
    dur = int(row["时长(小时)"])
    tid = row.get("_task_id", f"{row['曲目ID']}-{row['日期']}-{row['开始']}")
    gl = data.global_allowed.get(d, [])
    for s in range(slot, slot + dur):
        if s >= len(gl) or not gl[s]:
            _fail(f"{tid} {d} {SLOT_START_HOURS[s]:02d}:00 全局不允许")
if not any('❌' in e for e in _errors):
    _ok("所有排练时段均在全局允许范围内")

# ── 2. 到场成员可用性检验 ─────────────────────────────────────
print("\n[2] 到场成员可用性检验（缺席成员不检查）")
for row in _rows:
    d = row["日期"]
    slot = row.get("_slot_start", SLOT_START_HOURS.index(int(row["开始"].split(":")[0])))
    dur = int(row["时长(小时)"])
    tid = row.get("_task_id", f"{row['曲目ID']}-{row['日期']}-{row['开始']}")
    sid = row["曲目ID"]
    absent = row.get("缺席", "全员到齐")
    absent_m = absent if absent != "全员到齐" else ""
    present_members = [m for m in SONGS[sid]["members"] if m != absent_m]
    for m in present_members:
        avail = data.availability.get(m, {}).get(d, [])
        for s in range(slot, slot + dur):
            if s >= len(avail) or not avail[s]:
                _fail(f"{tid} {d} {SLOT_START_HOURS[s]:02d}:00 成员【{m}】不可用（但未标为缺席）")
_ok("所有到场成员在该时段均可用") if not _errors else None

# ── 3. 场次数量检验 ────────────────────────────────────────────
print("\n[3] 各曲目排练场次数量检验")
from collections import Counter
_session_count = Counter(row["曲目ID"] for row in _rows)
for sid in SONGS:
    expected = SONG_SESSION_OVERRIDE.get(sid, REQUIRED_DURATIONS[SONGS[sid]["difficulty"]])
    got = _session_count.get(sid, 0)
    if got != len(expected):
        _fail(f"曲目 {sid}({SONGS[sid]['name']}) 期望 {len(expected)} 场，实际 {got} 场")
    else:
        _ok(f"曲目 {sid}: {got} 场 ✓")

# ── 4. 时长检验 ────────────────────────────────────────────────
print("\n[4] 各场次时长检验")
_song_sessions = {}
for row in _rows:
    _song_sessions.setdefault(row["曲目ID"], []).append(int(row["时长(小时)"]))
for sid, durs in _song_sessions.items():
    expected = sorted(SONG_SESSION_OVERRIDE.get(sid, REQUIRED_DURATIONS[SONGS[sid]["difficulty"]]), reverse=True)
    actual = sorted(durs, reverse=True)
    if actual != expected:
        _fail(f"曲目 {sid} 时长 {actual} 与期望 {expected} 不符")
    else:
        _ok(f"曲目 {sid} 时长 {actual} ✓")

# ── 5. 每曲至少一次全员 ────────────────────────────────────────
print("\n[5] 每曲至少一次全员到齐检验")
for sid in SONGS:
    rows_sid = [r for r in _rows if r["曲目ID"] == sid]
    full = [r for r in rows_sid if r.get("缺席", "全员到齐") == "全员到齐"]
    if rows_sid and not full:
        _fail(f"曲目 {sid}({SONGS[sid]['name']}) 没有任何一次全员到齐")
    elif rows_sid:
        _ok(f"曲目 {sid}: {len(full)} 次全员到齐 ✓")

# ── 6. 每成员每曲最多缺席一次 ─────────────────────────────────
print("\n[6] 每成员每曲最多缺席一次检验")
_absence_count = {}
for row in _rows:
    sid = row["曲目ID"]
    absent = row.get("缺席", "全员到齐")
    if absent != "全员到齐":
        key = (sid, absent)
        _absence_count[key] = _absence_count.get(key, 0) + 1
for (sid, m), cnt in _absence_count.items():
    if cnt > 1:
        _fail(f"曲目 {sid} 成员【{m}】缺席 {cnt} 次（超过1次）")
_ok("所有成员每曲缺席不超过1次") if not any('❌' in e and '缺席' in e for e in _errors) else None

# ── 7. 9.19 最多1场 ────────────────────────────────────────────
print("\n[7] 9.19 场次数量检验")
_d919 = _dt_mod.date(2026, 9, 19)
_on919 = [r for r in _rows if r["日期"] == _d919]
if len(_on919) > 1:
    _fail(f"9.19 安排了 {len(_on919)} 场（超过1场）")
elif len(_on919) == 1:
    _ok(f"9.19 安排了 1 场：{_on919[0]['曲目ID']} {_on919[0]['开始']}–{_on919[0]['结束']} ✓")
else:
    _ok("9.19 无排练（在约束范围内）✓")

# ── 汇总 ──────────────────────────────────────────────────────
print("\n" + "=" * 60)
if _errors:
    print(f"❌ 发现 {len(_errors)} 个错误：")
    for e in _errors:
        print(e)
else:
    print(f"✅ 全部通过！共 {len(_rows)} 场排练，零错误。")
if _warnings:
    for w in _warnings:
        print(w)
print("=" * 60)



"""# OR-Tools 버전 호환 패치 (수정판)
from ortools.sat.python import cp_model as _cp_module

def _status_name_compat(self, status=None):
    if status is not None:
        if hasattr(status, 'name'):
            return status.name
        return str(status)
    try:
        internal = self._checked_response.status
        return internal.name if hasattr(internal, 'name') else str(internal)
    except Exception:
        return 'UNKNOWN'

_cp_module.CpSolver.StatusName = _status_name_compat
"""