// 与 design/tokens.css 保持一致;antd 需要具体色值来推导悬停 / 激活色,不能直接用 CSS 变量。
import type { ThemeConfig } from 'antd'

export const colors = {
  pink50: '#fef0fb',
  pink100: '#fcd5f4',
  pink300: '#f7a0d1',
  pink400: '#e59cc8',
  pink500: '#d97ab5',
  navy600: '#5369af',
  navy800: '#2f3f78',
  muted: '#6b6f8a',
  ok: '#4fb286',
  warn: '#f2a93b',
  error: '#e0557b',
}

export const theme: ThemeConfig = {
  token: {
    colorPrimary: colors.pink300,
    colorInfo: colors.navy600,
    colorLink: colors.navy600,
    colorLinkHover: colors.pink500,
    colorText: colors.navy800,
    colorTextSecondary: colors.muted,
    colorBorder: colors.navy600,
    colorBorderSecondary: colors.pink100,
    colorBgLayout: colors.pink100,
    colorBgContainer: '#ffffff',
    colorSuccess: colors.ok,
    colorWarning: colors.warn,
    colorError: colors.error,
    borderRadius: 12,
    borderRadiusLG: 20,
    borderRadiusSM: 8,
    fontFamily: "'Noto Sans SC', 'PingFang SC', system-ui, sans-serif",
    controlHeight: 40,
    lineWidth: 2,
  },
  components: {
    Button: {
      primaryColor: colors.navy800,
      colorPrimaryHover: colors.pink400,
      colorPrimaryActive: colors.pink500,
      fontWeight: 700,
      defaultBorderColor: colors.navy600,
      defaultColor: colors.navy800,
      defaultHoverColor: colors.navy800,
      defaultHoverBorderColor: colors.navy600,
      defaultHoverBg: colors.pink50,
      primaryShadow: 'none',
      defaultShadow: 'none',
    },
    Card: { headerBg: colors.pink50 },
    Table: {
      headerBg: colors.pink50,
      headerColor: colors.navy800,
      borderColor: colors.pink100,
      rowHoverBg: colors.pink50,
    },
    Tag: { defaultBg: colors.pink50, defaultColor: colors.navy800 },
    Input: { activeBorderColor: colors.navy600, hoverBorderColor: colors.pink400 },
    Select: { optionSelectedBg: colors.pink100 },
    Switch: { colorPrimary: colors.navy600, colorPrimaryHover: colors.navy800 },
    Segmented: { itemSelectedBg: colors.pink300, itemSelectedColor: colors.navy800 },
  },
}
